services:
  web:
    build: ./
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
