services:
  web:
    build: 
      context: ./
    container_name: django-web
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  pgdata:
  static:
  media: