name: Deploy to AWS
on:
  push:
    branches:
      - main
env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  DJANGO_PROD_ENV: ${{ secrets.DJANGO_PROD_ENV }}
  AWS_INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
  AWS_INSTANCE_USERNAME: ${{ secrets.AWS_INSTANCE_USERNAME }}

permissions: write-all

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    
    - name: Pull Recent git changes
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_INSTANCE_USERNAME }}@${{ env.AWS_INSTANCE_IP }} 'cd api && git pull origin main'

    - name: Set Django ENV
      run: |
        echo "${{ env.DJANGO_PROD_ENV }}" > .env.prod
        scp -i key.pem $(pwd)/.env.prod ${{ env.AWS_INSTANCE_USERNAME }}@${{ env.AWS_INSTANCE_IP }}:/home/${{ env.AWS_INSTANCE_USERNAME }}/api

    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_INSTANCE_USERNAME }}@${{ env.AWS_INSTANCE_IP }} 'docker compose -f "/home/${{ env.AWS_INSTANCE_USERNAME }}/api/docker-compose.prod.yml" down'

    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_INSTANCE_USERNAME }}@${{ env.AWS_INSTANCE_IP }} 'docker compose -f "/home/${{ env.AWS_INSTANCE_USERNAME }}/api/docker-compose.prod.yml" up -d --build'
